# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    # space, return line
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

    # python, yaml & json files format
    -   id: check-ast # python files
    -   id: check-yaml # yaml files
    -   id: check-json # json files

    # file size & merge conflict
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: check-merge-conflict
